image: node:4.4.3

services:
  - redis:latest
  - rethinkdb:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq curl
  - npm install
  - npm install forever -g
  - mkdir -p config
  - cp .gitlab-ci.config.json config/config.json

cache:
  paths:
    - node_modules/
    - config/

api:
  stage: test
  script:
    - forever start API.js
    - sleep 30
    - curl -I http://127.0.0.1:2000/
