kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: worker
    version: v1
  name: worker
  namespace: dermail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: rachel.sh/zllovesuki/dermail-api-worker:5.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1999
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1999
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /usr/src/app/config
      imagePullSecrets:
      - name: rachel-sh-login
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: api
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: api
    version: v1
  name: api
  namespace: dermail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: rachel.sh/zllovesuki/dermail-api:5.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 2000
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /usr/src/app/config
      imagePullSecrets:
      - name: rachel-sh-login
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: api
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: api
  name: api
  namespace: dermail
spec:
  type: ClusterIP
  ports:
  - name: API-Worker-Probe
    port: 2000
    targetPort: 2000
  selector:
    app: api
